import { readFile, mkdir, copyFile } from 'node:fs/promises';
import { Script } from 'node:vm';
import { fileURLToPath } from 'node:url';
const root = fileURLToPath(new URL('../', import.meta.url));
const html = await readFile(`${root}index.html`, 'utf8');
const scripts = [...html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g)];
if (scripts.length !== 3 || !html.includes('<script id="appearance-init">')) throw new Error('Expected appearance, embedded engine and game scripts.');
for (let i = 0; i < scripts.length; i++) new Script(scripts[i][1], { filename: `inline-script-${i + 1}.js` });
if (/<(?:script|link|img|audio|video)\b[^>]*(?:src|href)=["']https?:/i.test(html)) throw new Error('External runtime dependency found.');
if (/THREE_ENGINE|WORLD_CONTENT|GAME_SYSTEMS|INPUT_AND_RENDER/.test(html)) throw new Error('An unfinished source placeholder remains.');
await mkdir(`${root}dist`, { recursive: true });
await copyFile(`${root}index.html`, `${root}dist/index.html`);
console.log(`Built dist/index.html · ${(Buffer.byteLength(html) / 1024).toFixed(0)} KB · three valid embedded scripts · no external runtime assets.`);
